# Generated by Django 4.1.3 on 2022-11-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenets',
            name='degrees',
            field=models.IntegerField(blank=True, help_text='Only for servo', null=True),
        ),
    ]
